/**
 * Word Document Translations
 * Multilingual support for Word document generation
 */

const translations = {
  en: {
    // Identification section
    client: 'Client',
    company: 'Company',
    period: 'Period',
    identification: 'Identification',
    address: 'Address',
    contact: 'Contact',
    phone: 'Phone',
    email: 'Email',
    generatedBy: 'Generated by',
    createdOn: 'Created on',

    // Scope section
    scope: 'Scope',
    scopeDescription: 'This report covers {count} system(s) from {startDate} to {endDate}.',

    // Systems section
    systems: 'Systems',
    noSystems: 'No systems in this report.',
    processStages: 'Process Stages',
    systemPhotos: 'System Photos',

    // Table headers
    name: 'Name',
    type: 'Type',
    status: 'Status',
    description: 'Description',

    // Analyses section
    fieldMonitoringOverview: 'Field Monitoring Analysis – Overview',
    fieldMonitoringDetailed: 'Field Monitoring Analysis – Detailed',
    laboratoryMonitoringOverview: 'Laboratory Monitoring Analysis – Overview',
    laboratoryMonitoringDetailed: 'Laboratory Monitoring Analysis – Detailed',
    noFieldData: 'No field monitoring data available.',
    noLaboratoryData: 'No laboratory monitoring data available.',
    noDetailedData: 'No detailed analysis data available.',
    date: 'Date',
    system: 'System',
    user: 'User',
    entries: 'Entries',
    alerts: 'Alerts',
    parameter: 'Parameter',
    range: 'Range',

    // Charts
    fieldMonitoringCharts: 'Field Monitoring Charts',
    laboratoryMonitoringCharts: 'Laboratory Monitoring Charts',

    // Inspections section
    inspections: 'Inspections',
    noInspections: 'No inspections in this report.',
    noInspectionsWithNC: 'No inspections with non-conformities found.',
    inspectionsOverview: 'Inspections – Overview',
    inspectionsDetailed: 'Inspections – Detailed View',
    inspection: 'Inspection',
    inspector: 'Inspector',
    compliant: 'Compliant',
    nonCompliant: 'NC',
    item: 'Item',
    comment: 'Comment',
    conclusion: 'Conclusion',

    // Occurrences section
    occurrences: 'Occurrences',
    noOccurrences: 'No occurrences in this report.',
    noOccurrencesFiltered: 'No occurrences matching the filter criteria.',
    occurrencesOverview: 'Occurrences – Overview',
    occurrencesDetailed: 'Occurrences – Detailed View',
    showingOccurrences: 'Showing {filtered} of {total} occurrences.',
    timeline: 'Timeline',
    title: 'Title',
    priority: 'Priority',
    created: 'Created',
    resolved: 'Resolved',
    reporter: 'Reporter',
    assignedTo: 'Assigned to',
    comments: 'Comments',

    // Conclusion section
    reportSummary: 'Report Summary',
    totalSystems: 'Total Systems',
    totalAnalyses: 'Total Analyses',
    totalInspections: 'Total Inspections',
    totalOccurrences: 'Total Occurrences',
    alertsFound: 'Alerts Found',
    outOfRangeReadings: '{count} out of range readings',
    openIncidents: 'Open Incidents',
    conclusionText: 'Conclusion Text',
    noConclusionProvided: 'No conclusion provided for this report.',

    // Attachments section
    attachments: 'Attachments',
    attachmentsDescription: 'Additional documents and files can be attached here.'
  },

  pt: {
    // Identification section
    client: 'Cliente',
    company: 'Empresa',
    period: 'Período',
    identification: 'Identificação',
    address: 'Endereço',
    contact: 'Contato',
    phone: 'Telefone',
    email: 'E-mail',
    generatedBy: 'Gerado por',
    createdOn: 'Criado em',

    // Scope section
    scope: 'Escopo',
    scopeDescription: 'Este relatório cobre {count} sistema(s) de {startDate} a {endDate}.',

    // Systems section
    systems: 'Sistemas',
    noSystems: 'Nenhum sistema neste relatório.',
    processStages: 'Etapas do Processo',
    systemPhotos: 'Fotos do Sistema',

    // Table headers
    name: 'Nome',
    type: 'Tipo',
    status: 'Status',
    description: 'Descrição',

    // Analyses section
    fieldMonitoringOverview: 'Análise de Monitoramento de Campo – Visão Geral',
    fieldMonitoringDetailed: 'Análise de Monitoramento de Campo – Detalhada',
    laboratoryMonitoringOverview: 'Análise de Monitoramento Laboratorial – Visão Geral',
    laboratoryMonitoringDetailed: 'Análise de Monitoramento Laboratorial – Detalhada',
    noFieldData: 'Nenhum dado de monitoramento de campo disponível.',
    noLaboratoryData: 'Nenhum dado de monitoramento laboratorial disponível.',
    noDetailedData: 'Nenhum dado de análise detalhada disponível.',
    date: 'Data',
    system: 'Sistema',
    user: 'Usuário',
    entries: 'Entradas',
    alerts: 'Alertas',
    parameter: 'Parâmetro',
    range: 'Faixa',

    // Charts
    fieldMonitoringCharts: 'Gráficos de Monitoramento de Campo',
    laboratoryMonitoringCharts: 'Gráficos de Monitoramento Laboratorial',

    // Inspections section
    inspections: 'Inspeções',
    noInspections: 'Nenhuma inspeção neste relatório.',
    noInspectionsWithNC: 'Nenhuma inspeção com não conformidades encontrada.',
    inspectionsOverview: 'Inspeções – Visão Geral',
    inspectionsDetailed: 'Inspeções – Visão Detalhada',
    inspection: 'Inspeção',
    inspector: 'Inspetor',
    compliant: 'Conforme',
    nonCompliant: 'NC',
    item: 'Item',
    comment: 'Comentário',
    conclusion: 'Conclusão',

    // Occurrences section
    occurrences: 'Ocorrências',
    noOccurrences: 'Nenhuma ocorrência neste relatório.',
    noOccurrencesFiltered: 'Nenhuma ocorrência correspondente aos critérios de filtro.',
    occurrencesOverview: 'Ocorrências – Visão Geral',
    occurrencesDetailed: 'Ocorrências – Visão Detalhada',
    showingOccurrences: 'Mostrando {filtered} de {total} ocorrências.',
    timeline: 'Linha do Tempo',
    title: 'Título',
    priority: 'Prioridade',
    created: 'Criado',
    resolved: 'Resolvido',
    reporter: 'Relator',
    assignedTo: 'Atribuído a',
    comments: 'Comentários',

    // Conclusion section
    reportSummary: 'Resumo do Relatório',
    totalSystems: 'Total de Sistemas',
    totalAnalyses: 'Total de Análises',
    totalInspections: 'Total de Inspeções',
    totalOccurrences: 'Total de Ocorrências',
    alertsFound: 'Alertas Encontrados',
    outOfRangeReadings: '{count} leituras fora da faixa',
    openIncidents: 'Incidentes Abertos',
    conclusionText: 'Texto da Conclusão',
    noConclusionProvided: 'Nenhuma conclusão fornecida para este relatório.',

    // Attachments section
    attachments: 'Anexos',
    attachmentsDescription: 'Documentos e arquivos adicionais podem ser anexados aqui.'
  }
};

/**
 * Get translation helper function
 * @param {string} language - Language code ('en' or 'pt')
 * @param {string} key - Translation key
 * @param {object} params - Optional parameters for string interpolation
 * @returns {string} Translated text
 */
function t(language, key, params = {}) {
  const lang = language || 'pt'; // Default to Portuguese
  const translation = translations[lang]?.[key] || translations.pt[key] || key;

  // Simple string interpolation
  return translation.replace(/\{(\w+)\}/g, (match, param) => {
    return params[param] !== undefined ? params[param] : match;
  });
}

module.exports = {
  translations,
  t
};
